device: "cuda:0"
seed: 42

task:
  task_type: "retriever"
  query_type: "count"

experiments:
  results_path: "<PATH>" #TODO insert your path here

data:
  obj_id: 0   # 0 for all objects
  split: "val"
  data_path: "<PATH>" #TODO insert the path to the images here

retriever:
  clip_library: "openai"
  clip_model: "ViT-L/14@336px"
  t: 0.15
  stop_algo_type: "topk"
  k: 1000
  batch_size: 64
  num_workers: 16
  noisy_ir_noise: 300

processor:
  batch_size: 8
  checkpoint_processor: "OFA-Sys/ofa-large"

